### ISSUE TITLE
is it the right way to choose the algo for new users with edit distance of 80 % match ?

### ISSUE THREAD

**Issue by Nagesh8566** [marufaytekin/lsh-spark#13]
Can same algo can be used to get the NN of users with the same name with edit distance of 0.8 or so ?

**Comment by marufaytekin** [comment]
LSH parameters (b and r) need to be configured to retrieve the neighbors with the desired similarity level threshold, t. The threshold t is approximately (1/b)<sup>1/r</sup>.
