### ISSUE TITLE
problem of deserialization

### ISSUE THREAD

**Issue by bennybotbol** [marufaytekin/lsh-spark#14]
I have a cluster of 10 nodes + 1 driver,
--driver-memory 2200m
--executor-memory 3500m
--executor-cores 1

I take the Big MovieLens DataSet
http://files.grouplens.org/datasets/movielens/ml-latest.zip

I unzip it on the HDFS and put it on my HDFS

I load my RDD Of Ratings using this function
`
  def get_rdd_ratings_long_ML(sc: SparkContext, dataFile: String, numPartitions: Int): RDD[(Int, Int, Double)] = {
    val data = sc.textFile(dataFile, numPartitions)

    //parse data and create (user, item, rating) tuples
    data
      .map(line => line.split(","))
      .map(elems => (elems(0).toInt, elems(1).toInt, elems(2).toDouble))
  }

val dataFile = "/tmp/lsh/lsh/ml-latest/ratings.csv"
val numPartitions = 10
val numHashFunctions = 15
val numHashTables = 10

val rddRatings = get_rdd_ratings_long_ML(sc,dataFile,numPartitions)

//I prepare the data to retrieve (users:RDD[Long],items:RDD[Long], sparseVectorDta:RDD[(Long,SparseVector)])
//using the prepare_data function:

def prepare_data(ratingsRDD: RDD[(Int, Int, Double)]) = {
    println("count nb ratings:" + ratingsRDD.count)

    //list of distinct items
    val items = ratingsRDD.map(x => x._2).distinct()
    println("count nb items:" + items.count)
    val maxIndex = items.max + 1

    val users = ratingsRDD.map(x => x._1).distinct()
    println("count nb users:" + users.count)

    //user ratings grouped by user_id
    val userItemRatings = ratingsRDD.map(x => (x._1, (x._2, x._3))).groupByKey().cache()

    //convert each user's rating to tuple of (user_id, SparseVector_of_ratings)
    val sparseVectorData = userItemRatings
      .map(a => (a._1.toLong, Vectors.sparse(maxIndex, a._2.toSeq).asInstanceOf[SparseVector]))

    (users, items, sparseVectorData.cache().setName("sparseVectorData"))
  }

//gtting the length of the sparseVectors
val maxIndex = items.max + 1

import com.lendap.spark.lsh.LSHModel
import com.lendap.spark.lsh.LSH

//creating the model
val lsh = new LSH(sparseVectorData, maxIndex, numHashFunctions, numHashTables)
val model = lsh.run()
//creating` a sample vector
val svuser = Main.get_sample_vector(maxIndex)

//getting the Candidates
val rddCand = model.getCandidates(svuser)

//collecting , in order to get a List i Can filter my SparseVectorRDD with
rddCand.collect()
`
//this takes 6 seconds to deserialize.Where does this deserialization time comes from?

**Comment by marufaytekin** [comment]
>collect() `returns all the elements of the dataset as an array at the driver program. This is usually useful after a filter or other operation that returns a sufficiently small subset of the data.`

Do you know the size of your rddCand list? It might be too big and takes 6 seconds.
