### ISSUE TITLE
how to user this method to deal with 1 billion node and  300 features? 

### ISSUE THREAD

**Issue by lazybonesboy** [marufaytekin/lsh-spark#16]
if Hash function numbers is 100,  then  the average of every bucket's size is about 100000 ( = 1 billion /(100*99)). this number is still bigger to compute cosine similarity. can you list  the up threshold  of this method  to deal with the node number.

**Comment by marufaytekin** [comment]
LSH has two parameters: 
- Number of hash tables (L)
- Number of hash functions (k)

In our model, there approximately will be 2^k buckets in each hash table. And your data will be grouped into these buckets. These parameters should be optimized for your model/data. You can see more information in section 3.4.3 of Mining of Massive Datasets book.

Can you define 1 billion node and 300 features and the similarity calculation you are trying to compute? Can you also explain what you mean by "hash function numbers"?

**Comment by lazybonesboy** [comment]
OK, Get it.  I got wrong with the formula of every bucket.  It's 2^K not K*(K-1).  "hash function numbers" is the number of has functions. And I use cosine similarity to compute. Thank YOU.

**Comment by marufaytekin** [comment]
Now let's state the problem:
- You have 1 billion data points with 300 features. Let n = 10^9 and m = 300
- You want to use cosine similarity with LSH to find the similar data points.

This is how I understand your problem. Please correct if it is wrong.

You can follow these steps to find the similar data points:

1. First, you need to set/select LSH properties(these parameters can/should be optimized for your problem). Let's say you set number of hash functions to 10 (k=10) and number of hash tables to 1 (L=1)

2. In this scenario, based on our approach of using cosine similarity, you will have approximately 2^k = 2^10 = 1024 buckets.

3. You hash each data point to a bucket by calculating a hash key for each data point. The complexity of this operation is O(nmk). 

4. Now, you distributed 1 billion data points to 1024 buckets. Each bucket will approximately have 10^9/1024 = 976562 data points. Each bucket has similar (clustered) data points in it. You built your model.

5. Let's say you want to find the top 5 similar data points for a target data point in your model.
Here is how you can find the top 5 similar data points for a target data point:
-- Compute a hash key for the target data point and map it to a bucket. This means this dat apoint is similar to data points in this bucket.
-- Compute a cosine similarity between target data point and the data points in this bucket.
-- Select the top-5 most similar among these data points.
-- In this scenario, you will approximately compare your target data point with 976562 data points in the bucket it maps to.
-- If you want to reduce the number of comparisons, you can increase the number of hash functions, k. If you set k = 24 you will end up with 2^16 = 65536 buckets. Then each bucket will approximately have 15258 (10^9 / 65536) data points. In this scenario, you will compare your target data point with only 65536 data points. 
-- You can optimize these parameters (k, L) for the accuracy and the speed.

You can also check the slide 11,12,13,14 in the slides here: https://www.slideshare.net/MarufAytekin/scalable-recommendation-algorithms-with-lsh

I hope this helps.
Maruf
